<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Stepwise.WindowsIntegration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stepwise.Core\Stepwise.Core.csproj" />
  </ItemGroup>

</Project>
