"""Message generation: prompt building, provider chain, quality gate, template fallback.

Flow (spec §16): try Groq -> try OpenRouter -> curated templates. Every candidate is
checked by the quality gate; the first one that passes is returned together with its
source label so the message log records where it came from.

V4: the Friend register draws a sub-mode (comment/memory/question/joke) so questions stay
rare; the memory mode references stored life-facts passed in by the caller. The Philosopher
serves a verified quote or fact verbatim part of the time (the model never invents either).
"""
from __future__ import annotations

import json
import logging
import random
import re

from . import db, llm, quality
from .config import Settings
from .roles import FRIEND_FORMS, ROLES, RoleSpec, Window, pick_friend_mode
from .templates import friend_templates, random_verified, templates_for

logger = logging.getLogger(__name__)

ATTEMPTS_PER_PROVIDER = 2
# How often the Philosopher serves a hand-checked quote/fact verbatim vs a model-written
# observation. Quotes and facts are never generated by the model (the gate blocks attributions
# and the model would hallucinate facts) — they come only from the curated base. V4 leans the
# register toward those curated lines, so the verbatim share is the majority.
PHILOSOPHER_VERBATIM_SHARE = 0.6
# How many stored facts to weave into a single Friend "memory" message.
MEMORY_FACTS_PER_MESSAGE = 2


def _system_prompt(role: RoleSpec) -> str:
    return (
        "Ты — Echo, близкий друг одного человека в Telegram. Ты иногда пишешь ему "
        "первым — коротко, как живой человек, а не как бот или цитатник.\n"
        f"Сейчас твоя интонация — «{role.name}»: {role.persona}.\n"
        "Правила:\n"
        f"- Коротко. Одна мысль или один вопрос. Часто — одно предложение. {role.length_hint}.\n"
        "- Точно держись своей интонации: по форме и теме это сообщение должно быть ни с "
        "чем не спутать. Не превращай его в обычный дружеский вопрос, если роль другая.\n"
        "- По-русски, разговорно и тепло, без приторности и без робота.\n"
        "- Ни в коем случае не похоже на: мотивацию, коучинг, самопомощь, философский "
        "паблик, Jira-бота, фитнес-трекер, HR- или AI-ассистента. Ты живой знакомый человек.\n"
        "- Никаких цитат и имён авторов от себя — ты их не выдумываешь.\n"
        "- Без штампов («верь в себя», «всё получится») и без фраз, которые подошли бы любому в интернете.\n"
        "- Без приветствий и обращения по имени — сразу по сути.\n"
        "Перед отправкой проверь: «Это реально написал бы живой человек своему знакомому?» "
        "Если нет — переформулируй.\n"
        "Верни только текст сообщения, без кавычек и пояснений."
    )


def _user_prompt(role: RoleSpec, window: Window, recent: list[str], form: str | None = None) -> str:
    lines = [f"Время суток: {window.label}. Контекст: {window.hint}."]
    if recent:
        joined = " | ".join(recent[:4])
        lines.append(f"Недавно уже было: {joined}. Не повторяй эти темы и формулировки.")
    # The form is the only role-specific instruction — it decides topic and shape, so each
    # register (and each Friend sub-mode) stays identifiable from a single message.
    lines.append(form if form is not None else role.form)
    return "\n".join(lines)


def _sample_facts(facts: list[str] | None) -> list[str]:
    if not facts:
        return []
    return random.sample(facts, min(MEMORY_FACTS_PER_MESSAGE, len(facts)))


def _friend_form_and_sub(facts: list[str] | None) -> tuple[str, str]:
    """Pick a Friend sub-mode and its form. Memory falls back to comment when no facts exist."""
    sub = pick_friend_mode()
    if sub == "memory":
        chosen = _sample_facts(facts)
        if not chosen:
            sub = "comment"
        else:
            form = FRIEND_FORMS["memory"] + "\nФакты о нём: " + "; ".join(chosen) + "."
            return form, "memory"
    return FRIEND_FORMS[sub], sub


def _effective_form(role_key: str, facts: list[str] | None) -> tuple[str, str | None]:
    """Return (form, friend_sub). friend_sub is the template sub-bank to fall back to, or None."""
    if role_key == "friend":
        return _friend_form_and_sub(facts)
    return ROLES[role_key].form, None


def _providers(settings: Settings) -> list[tuple[str, str, str, str]]:
    """(source_label, base_url, api_key, model) for each configured backend, in order."""
    chain: list[tuple[str, str, str, str]] = []
    if settings.groq_api_key:
        chain.append(("llm-groq", settings.groq_base_url, settings.groq_api_key, settings.groq_model))
    if settings.openrouter_api_key:
        chain.append(
            ("llm-openrouter", settings.openrouter_base_url, settings.openrouter_api_key, settings.openrouter_model)
        )
    return chain


def _pick_template(role_key: str, recent: list[str], friend_sub: str | None = None) -> str:
    bank = friend_templates(friend_sub) if role_key == "friend" and friend_sub else templates_for(role_key)
    if not bank:
        bank = ["Просто отмечаюсь рядом."]
    fresh = [t for t in bank if not quality.is_too_similar(t, recent)]
    return random.choice(fresh) if fresh else random.choice(bank)


async def generate_message(
    settings: Settings, role_key: str, window: Window, recent: list[str],
    temperature: float = 0.9, facts: list[str] | None = None,
) -> tuple[str, str]:
    """Return (text, source). Source is 'verified' / 'llm-*' / 'template'."""
    role = ROLES[role_key]

    # Philosopher: most of the time serve a hand-checked quote/fact verbatim; otherwise the
    # model writes a plain observation (any quote/fact it tries to invent is rejected below).
    if role_key == "philosopher" and random.random() < PHILOSOPHER_VERBATIM_SHARE:
        verbatim = random_verified()
        if not quality.is_too_similar(verbatim, recent):
            return verbatim, "verified"

    form, friend_sub = _effective_form(role_key, facts)
    system = _system_prompt(role)
    user = _user_prompt(role, window, recent, form)

    for source, base_url, api_key, model in _providers(settings):
        for _ in range(ATTEMPTS_PER_PROVIDER):
            text = await llm.chat(
                base_url=base_url, api_key=api_key, model=model,
                system=system, user=user, temperature=temperature, title="Echo companion",
            )
            if not text:
                break  # provider unavailable — move to the next one
            text = text.strip().strip('"').strip()
            ok, reason = quality.check(text, role_key, recent)
            if ok:
                return text, source
            logger.info("Rejected %s candidate (%s)", source, reason)

    return _pick_template(role_key, recent, friend_sub), "template"


async def generate_followup(
    settings: Settings, user_message: str, temperature: float = 0.8
) -> str | None:
    """React to something the user said. None -> caller stays silent.

    Character Bible priority #1: when the user shares about his life, Echo reacts as a
    friend who is genuinely curious about him — NOT by deepening its own prior thought.
    A short question about *him* beats any new wisdom. The previous role is irrelevant.
    """
    system = (
        "Ты — Echo, близкий друг одного человека. Он только что написал тебе о своей жизни.\n"
        "Отреагируй как живой друг, которому искренне интересен именно он.\n"
        "Правила:\n"
        "- Приоритет №1 — интерес к нему. Чаще всего это короткий вопрос про то, что он рассказал.\n"
        "- Реагируй на то, ЧТО он сказал. Не вставляй свою мысль, не философствуй, не поучай, не давай советов.\n"
        "- Рад — порадуйся коротко и спроси про детали. Устал — мягко, без советов. Успех — отметь и спроси, как он.\n"
        "- Только если он явно застрял или жалуется на проблему — можешь задать один аккуратный неудобный вопрос. "
        "Иначе просто тёплый интерес.\n"
        "- Одна короткая фраза или один вопрос. По-русски, разговорно, без штампов и без обращения по имени.\n"
        "Верни только текст, без кавычек."
    )
    user = f"Он написал: «{user_message}»"
    for _source, base_url, api_key, model in _providers(settings):
        text = await llm.chat(
            base_url=base_url, api_key=api_key, model=model,
            system=system, user=user, temperature=temperature, title="Echo companion",
        )
        if text:
            text = text.strip().strip('"').strip()
            ok, _reason = quality.check(text, "friend", [user_message])
            if ok:
                return text
    return None


# --- fact extraction: learn durable life-facts from what the owner writes -----

_FACT_EXTRACTION_SYSTEM = (
    "Ты извлекаешь устойчивые личные факты о человеке из его сообщения.\n"
    "Устойчивые факты: люди в его жизни (девушка, друзья, семья), работа, учёба, спорт, "
    "важные планы и события, поездки, увлечения.\n"
    "НЕ извлекай: сиюминутное настроение, усталость, разовые мелочи, общие фразы.\n"
    "Верни ТОЛЬКО JSON-массив коротких фактов на русском, например "
    '["есть девушка", "занимается спортом"]. Если устойчивых фактов нет — верни []. '
    "Максимум 3 факта, каждый короткий."
)

_JSON_ARRAY_RE = re.compile(r"\[.*\]", re.DOTALL)
_MAX_FACT_LEN = 120


def _parse_facts(text: str) -> list[str]:
    match = _JSON_ARRAY_RE.search(text)
    if not match:
        return []
    try:
        data = json.loads(match.group(0))
    except (ValueError, TypeError):
        return []
    if not isinstance(data, list):
        return []
    facts: list[str] = []
    for item in data:
        if isinstance(item, str):
            fact = item.strip()
            if 0 < len(fact) <= _MAX_FACT_LEN:
                facts.append(fact)
    return facts[:3]


async def extract_and_store_facts(settings: Settings, user_message: str, now_iso: str) -> list[str]:
    """Pull durable facts from the owner's message and store new ones. [] when no model/keys."""
    providers = _providers(settings)
    if not providers:
        return []
    user = f"Сообщение: «{user_message}»"
    for _source, base_url, api_key, model in providers:
        text = await llm.chat(
            base_url=base_url, api_key=api_key, model=model,
            system=_FACT_EXTRACTION_SYSTEM, user=user, temperature=0.2, title="Echo facts",
        )
        if not text:
            continue
        stored = [f for f in _parse_facts(text) if db.add_fact(f, now_iso) is not None]
        return stored
    return []
